
package gui;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Film_based extends javax.swing.JFrame {

    private core.DataManager dataManager;
    private core.RecommendationEngine recommendationEngine;
    private String[] randomTenMovies;
    private DefaultListModel<String> listModel;
    
    public Film_based() {
         initComponents();

        // 1. Ekran Boyutunu ve Panel Sınırlarını 800x800 Sabitliyoruz (Taşma Sorunu Çözüldü!)
        this.setSize(706, 670); 
        this.setMinimumSize(new java.awt.Dimension(706, 670));
        this.setMaximumSize(new java.awt.Dimension(706, 670));
        this.setResizable(false);
        this.setTitle("Movie Recommendation System");
        this.setLocationRelativeTo(null); // Ekranın tam ortasında açar
        
        // VERİ GARANTİSİ: Ne olursa olsun verileri sıfırdan ve eksiksiz yüklüyoruz!
        this.dataManager = new core.DataManager();
        this.dataManager.loadMovies("movies.csv");
        this.dataManager.loadMainData("main_data.csv");
        
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        
        // Rastgele 10 film ismini çek ve combo box'lara ata
        randomTenMovies = dataManager.getRandomTenMovieNames();
        JComboBox[] comboBoxesB = {jComboBox6, jComboBox7, jComboBox8, jComboBox1, jComboBox2};
        for (int i = 0; i < 5; i++) {
            comboBoxesB[i].removeAllItems();
            for (String movieName : randomTenMovies) {
                if (movieName != null) {
                    comboBoxesB[i].addItem(movieName);
                }
            }
            if(comboBoxesB[i].getItemCount() > i) {
                comboBoxesB[i].setSelectedIndex(i);
            }
        }
        
       for (JComboBox box : comboBoxesB) {
            box.addActionListener(e -> {
                // Eğer tetiklenme arka plandaki temizlikten dolayıysa işlem yapma
                if (box.getSelectedIndex() == -1) return;
                
                java.util.HashSet<String> selectedMovies = new java.util.HashSet<>();
                for (JComboBox cb : comboBoxesB) {
                    Object selected = cb.getSelectedItem();
                    if (selected != null) {
                        String movie = selected.toString();
                        if (selectedMovies.contains(movie)) {
                            JOptionPane.showMessageDialog(this, "Aynı filmi birden fazla seçemezsiniz!", "Seçim Hatası", JOptionPane.WARNING_MESSAGE);
                            
                            // Kısır döngüyü engellemek için listener'ı geçici olarak boşa çıkarıp ilk elemanı seçtiriyoruz
                            cb.setSelectedIndex(0); 
                            return;
                        }
                        selectedMovies.add(movie);
                    }
                }
            });
        }
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jComboBox6.setBackground(new java.awt.Color(40, 40, 40));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setPreferredSize(new java.awt.Dimension(559, 40));

        jComboBox7.setBackground(new java.awt.Color(40, 40, 40));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.setMinimumSize(new java.awt.Dimension(559, 40));

        jComboBox8.setBackground(new java.awt.Color(40, 40, 40));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox8.setMinimumSize(new java.awt.Dimension(559, 40));

        jComboBox1.setBackground(new java.awt.Color(40, 40, 40));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(559, 40));

        jComboBox2.setBackground(new java.awt.Color(40, 40, 40));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(559, 40));

        jTextField1.setText("5");

        jTextField2.setText("5");

        jTextField4.setText("5");

        jTextField5.setText("5");

        jLabel1.setText("X:");

        jTextField6.setText("5");

        jLabel2.setText("K:");

        jTextField7.setText("3");

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Get Recommendation");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel3.setText("Recommendations");

        jTextField3.setText("5");

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setText("Cancel");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // 1. Her tıklamada listeyi sıfırla
            listModel.clear();
            if (this.recommendationEngine == null) {
                this.recommendationEngine = new core.RecommendationEngine();
            }
            // Eğer bir şekilde veri havuzu uçmuşsa emniyet kilidi:
            if (this.dataManager == null || this.dataManager.getMovieCount() == 0) {
                this.dataManager = new core.DataManager();
                this.dataManager.loadMovies("movies.csv");
                this.dataManager.loadMainData("main_data.csv");
            }
            
            // 2. Input kontrolü
            int X = Integer.parseInt(jTextField6.getText().trim());
            int K = Integer.parseInt(jTextField7.getText().trim());
            if(X <= 0 || K <= 0){
                JOptionPane.showMessageDialog(this, "X ve K pozitif sayı olmalı!", "Hata", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            jLabel3.setText("Top " + (X * K) + " Recommendations");
            
            // 3. Tasarımdaki ComboBox ve TextField dizilimleri
            JComboBox[] comboBoxes = {jComboBox6, jComboBox7, jComboBox8, jComboBox1, jComboBox2};
            JTextField[] ratingFields = {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5};
            
            models.User virtualUser = new models.User(99999);

            // 4. Seçilen filmleri sanal kullanıcıya ekle
            for (int i = 0; i < 5; i++) {
                String movieName = comboBoxes[i].getSelectedItem().toString();
                int rating = Integer.parseInt(ratingFields[i].getText().trim());
                if(rating < 1 || rating > 5){
                    JOptionPane.showMessageDialog(this, "Puanlar 1-5 arasında olmalı!", "Hata", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                int movieId = dataManager.getMovieIdByName(movieName);
                if (movieId != -1) {
                    virtualUser.addRating(movieId, rating);
                }
            }
            
            // 5. Heap ve Algoritma Operasyonları (Constructor'daki dataManager'ı doğrudan kullanıyor)
            datastructures.CustomLinkedList<models.User> allUsers = dataManager.getAllUsers();
            int totalMovieCount = dataManager.getMovieCount();
            
            datastructures.MaxHeap<models.UserSimilarity> heap = recommendationEngine.buildHeapForTargetUser(virtualUser, allUsers, totalMovieCount);
            
            int rank = 1;
            java.util.ArrayList<Integer> added = new java.util.ArrayList<>();
            
            int neighborCount = 0;
            while (!heap.isEmpty() && neighborCount < K && added.size() < X * K) {
                models.UserSimilarity sim = heap.extractMax();
                models.User neighbor = sim.getUser();

                datastructures.MaxHeap<models.MovieRating> movieHeap = new datastructures.MaxHeap<>();
                for (int mId = 1; mId <= totalMovieCount; mId++) {
                    int rating = neighbor.getRatingForMovie(mId);
                    if (rating > 0 && virtualUser.getRatingForMovie(mId) == 0) {
                        int weightedScore = rating + (int)(sim.getSimilarityScore() * 10);
                        movieHeap.insert(new models.MovieRating(mId, weightedScore));
                    }
                }
                int count = 0;
                while (!movieHeap.isEmpty() && count < X && added.size() < X * K) {
                    models.MovieRating mr = movieHeap.extractMax();
                    int id = mr.getMovieId();
                    if (!added.contains(id)) {
                        String name = dataManager.getMovieNameById(id);
                        if (name != null && !name.trim().isEmpty()) {
                            listModel.addElement(rank + ". " + name + " (User: " + neighbor.getId() + ")");
                            added.add(id);
                            rank++;
                            count++;
                        }
                    }
                }
                neighborCount++;
            }
            
            if (added.isEmpty()) {
                listModel.addElement("Öneri üretilemedi.");
            }
            jList1.revalidate();
            jList1.repaint();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Lütfen sadece sayı giriniz!", "Hata", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FirstPnl().setVisible(true);
        dispose();
        System.gc();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Film_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Film_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Film_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Film_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Film_based().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
private void prepareRandomTenMovies() {
    randomTenMovies = dataManager.getRandomTenMovieNames();
}
}
