
package gui;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class User_Based extends javax.swing.JFrame {

    
    private core.DataManager dataManager;
    private core.RecommendationEngine recommendationEngine;
    private DefaultListModel<String> listModel;
    
    public User_Based() {
        initComponents();
      
        // === VERİ YAPISI VE MOTOR BAĞLANTILARI ===
        this.dataManager = new core.DataManager();
        this.recommendationEngine = new core.RecommendationEngine();
        this.setLocationRelativeTo(null);
        dataManager.loadMovies("movies.csv");
        dataManager.loadMainData("main_data.csv");
        dataManager.loadTargetUsers("target_user.csv");
        
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);

        // ComboBox Doldurma İşlemi
        cmpTargetUsers.removeAllItems();
        datastructures.CustomLinkedList<Integer> targetIds = dataManager.getTargetUserIds();
        datastructures.CustomLinkedList.Node<Integer> currNode = targetIds.getHead();
        
        while (currNode != null) {
            String idStr = currNode.data.toString();
            boolean alreadyExists = false;
            for (int i = 0; i < cmpTargetUsers.getItemCount(); i++) {
                if (cmpTargetUsers.getItemAt(i).toString().equals(idStr)) {
                    alreadyExists = true;
                    break;
                }
            }
            if (!alreadyExists) {
                cmpTargetUsers.addItem(idStr); 
            }
            currNode = currNode.next;
        }
        
        // Arayüzü tazeleyip ekrana bas
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmpTargetUsers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Target User:");

        cmpTargetUsers.setBackground(new java.awt.Color(40, 40, 40));
        cmpTargetUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("X:");

        jTextField1.setText("5");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("K:");

        jTextField2.setText("3");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Top");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("X*K");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Recommendations");

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Get Recommendations");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cancel");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpTargetUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(65, 65, 65)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmpTargetUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    dataManager.resetUserRatingsForNextSearch();
        if (cmpTargetUsers.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Lütfen bir hedef kullanıcı seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // ÖDEV İSTERLERİNE %100 UYUM:
        // X = En benzer kaç kullanıcı (komşu) seçilecek
        // K = Her kullanıcıdan kaç adet en yüksek puanlı film listelenecek
        int X = Integer.parseInt(jTextField1.getText().trim()); 
        int K = Integer.parseInt(jTextField2.getText().trim()); 
        
        if(X <= 0 || K <= 0){
            JOptionPane.showMessageDialog(this, "X ve K pozitif sayı olmalı!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int targetId = Integer.parseInt(cmpTargetUsers.getSelectedItem().toString());
        jLabel5.setText(String.valueOf(X * K)); // Toplam X * K kadar film listelenecek
        listModel.clear(); // Eski listeyi temizle
        
        models.User targetUser = null;
        datastructures.CustomLinkedList<models.User> allUsers = dataManager.getAllUsers();
        
        // ÖZGÜN ID SENKRONİZASYONU:
        // Target ID'ler (601-610) arasındayken ana verideki indexler (1-600) arasındadır.
        // Aradaki 600 farkı offset olarak çıkartıp eşleşen matris satırını buluyoruz.
        int mappedId = targetId - 600; 
        
        // Ana listeden gerçek User nesnesini cımbızla çekiyoruz
        datastructures.CustomLinkedList.Node<models.User> userSearch = allUsers.getHead();
       
       
    while(userSearch != null) {
        int currentUserId = userSearch.data.getId();
        // Hem 1-10 arası indexi hem de 601-610 arası gerçek ID'yi kontrol eder, hata riskini sıfırlar
        if (currentUserId == mappedId || currentUserId == targetId) {
            targetUser = userSearch.data;
            break;
        }
        userSearch = userSearch.next;
    }
        
        if (targetUser == null) {
            JOptionPane.showMessageDialog(this, "Hedef kullanıcı main_data içinde bulunamadı!");
            return;
        }
        
        int totalMovieCount = dataManager.getMovieCount(); 
        
        // ii. ve iii. Maddeler: Cosine similarity hesaplanıp tüm kullanıcılar Heap'e diziliyor
        datastructures.MaxHeap<models.UserSimilarity> similarityHeap = recommendationEngine.buildHeapForTargetUser(targetUser, allUsers, totalMovieCount);

        int rank = 1;
        java.util.ArrayList<Integer> addedMovieIds = new java.util.ArrayList<>();

        // iv. Madde: En benzer X adet kullanıcıyı (komşuyu) çekiyoruz
        int userCount = 0;
        while (!similarityHeap.isEmpty() && userCount < X) { 
            models.UserSimilarity topSim = similarityHeap.extractMax();
            models.User neighbor = topSim.getUser();
            double simScore = topSim.getSimilarityScore(); 

            datastructures.MaxHeap<models.MovieRating> movieHeap = new datastructures.MaxHeap<>();
            
            for(int mId = 1; mId <= totalMovieCount; mId++){
                int neighborRating = neighbor.getRatingForMovie(mId);
                
                // Eğer komşu bu filmi izlediyse ve hedef kullanıcı henüz hiç izlemediyse
                if(neighborRating > 0 && targetUser.getRatingForMovie(mId) == 0){
                    
                    // ÖZGÜN ZITLIK VE AYNA MANTIĞI:
                    // Puanı -3 yönüne çekip benzerlik skoruyla yönlü çarpım yapıyoruz
                    double directionFactor = neighborRating - 3;
                    double calculation = simScore * directionFactor;
                    int finalSimulatedRating = (int)(calculation + 3);
                    
                    if (finalSimulatedRating > 0) {
                        movieHeap.insert(new models.MovieRating(mId, finalSimulatedRating));
                    }
                }
            }
            
            // iv. Madde Devamı: Her komşunun yığınından en yüksek puanlı K adet filmi çekiyoruz
            int moviesAddedFromNeighbor = 0;
            while(!movieHeap.isEmpty() && moviesAddedFromNeighbor < K && addedMovieIds.size() < (X * K)){
                models.MovieRating topMovie = movieHeap.extractMax();
                int movieId = topMovie.getMovieId();
                
                if(!addedMovieIds.contains(movieId)){
                    // v. Madde: Film ID'si yerine movies.csv'den çekilen Film Adı listeleniyor
                    String movieName = dataManager.getMovieNameById(movieId);
                    if(movieName != null && !movieName.trim().isEmpty() && !movieName.equalsIgnoreCase("unknown")){
                        listModel.addElement(rank + ". " + movieName + " (Tahmini Puan: " + topMovie.getRating() + ")");
                        addedMovieIds.add(movieId);
                        rank++;
                        moviesAddedFromNeighbor++;
                    }
                }
            }
            userCount++; 
        }
        
        if (addedMovieIds.isEmpty()) {
            listModel.addElement("Önerilecek film bulunamadı.");
        }
        
        jList1.revalidate();
        jList1.repaint();
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Lütfen parametre alanlarına geçerli tam sayılar giriniz!");
    } catch (java.awt.HeadlessException ex) {
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FirstPnl().setVisible(true);
        dispose();
        System.gc();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Based().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmpTargetUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
